import "./globals.css";
import Provider from '@/app/reduxProvider'
import Navbar from "./components/navbar";
import Footer from "./components/footer";
import Banner from "./pages/banners";


export const metadata = {
  title: "Astral Paints",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Provider>
        <Navbar />
        {children}
        <Footer />
        
        </Provider>
      </body>
    </html>
  );
}
